import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const fontPoppins = Nunito({
  variable: "--font-poppins",
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
