import React from 'react'
import { BookProvider } from '../../context/BooksContext'

import { Metadata } from 'next';
import Header from '../../components/pages/home/Header';

import GridLayout from '../../components/pages/home/GridLayout';

export const metadata: Metadata = {
  title: "Bem Vindo ao BookWise",
  description: "Generated by create next app",
};

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <BookProvider>
      <GridLayout>
        <Header />
        <div id="grid-area-content">
          {children}
        </div>
      </GridLayout>
    </BookProvider>
  )
}
