import React from 'react'
import { BookProvider } from './Context/BooksContext'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Bem Vindo ao BookWise",
  description: "Generated by create next app",
};

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <div>
      <BookProvider>
        {children}
      </BookProvider>
    </div>
  )
}
